---
- block:
    - name: Read Database Configuration
      k8s_info:
        kind: Secret
        namespace: '{{ meta.namespace }}'
        name: '{{ tower_postgres_configuration_secret }}'
      register: postgres_configuration

    - name: Store Database Configuration
      set_fact:
        awx_postgres_user: "{{ postgres_configuration['resources'][0]['data']['username'] | b64decode }}"
        awx_postgres_pass: "{{ postgres_configuration['resources'][0]['data']['password'] | b64decode }}"
        awx_postgres_database: "{{ postgres_configuration['resources'][0]['data']['database'] | b64decode }}"
        awx_postgres_port: "{{ postgres_configuration['resources'][0]['data']['port'] | b64decode }}"
        awx_postgres_host: "{{ postgres_configuration['resources'][0]['data']['host'] | b64decode }}"

  when:
    - external_database | bool
    - tower_postgres_configuration_secret

- block:
    - name: Assert that all the required parameters are specified
      assert:
        that:
          - tower_postgres_user
          - tower_postgres_pass
          - tower_postgres_database
          - tower_postgres_port
          - tower_postgres_host

    - name: Store Database Configuration
      set_fact:
        awx_postgres_user: "{{ tower_postgres_user }}"
        awx_postgres_pass: "{{ tower_postgres_pass }}"
        awx_postgres_database: "{{ tower_postgres_database }}"
        awx_postgres_port: "{{ tower_postgres_port }}"
        awx_postgres_host: "{{ tower_postgres_host }}"

  when:
    - external_database | bool
    - not tower_database_configuration_secret

- block:
    - name: Read Database Configuration
      k8s_info:
        kind: Secret
        namespace: '{{ meta.namespace }}'
        name: '{{ meta.name }}-postgres-configuration'
      register: postgres_config_resources

    - name: Store Database Configuration
      set_fact:
        awx_postgres_user: "{{ postgres_configuration['resources'][0]['data']['username'] | b64decode }}"
        awx_postgres_pass: "{{ postgres_configuration['resources'][0]['data']['password'] | b64decode }}"
        awx_postgres_database: "{{ postgres_configuration['resources'][0]['data']['database'] | b64decode }}"
        awx_postgres_port: "{{ postgres_configuration['resources'][0]['data']['port'] | b64decode }}"
        awx_postgres_host: "{{ postgres_configuration['resources'][0]['data']['host'] | b64decode }}"

  when:
    - external_database | bool
    - awx_postgres_user | default('')

- block:
    - name: Create Database configuration
      k8s:
        apply: yes
        definition: "{{ lookup('template', 'tower_postgres_secret.yaml.j2') }}"
      register: k8s_postgres_config_result

    - name: Create Database
      k8s:
        apply: yes
        definition: "{{ lookup('template', 'tower_postgres.yaml.j2') }}"
      register: k8s_postgres_result

    - name: Read Database Configuration
      k8s_info:
        kind: Secret
        namespace: '{{ meta.namespace }}'
        name: '{{ meta.name }}-postgres-configuration'
      register: postgres_configuration

    - name: Store Database Configuration
      set_fact:
        awx_postgres_user: "{{ postgres_configuration['resources'][0]['data']['username'] | b64decode }}"
        awx_postgres_pass: "{{ postgres_configuration['resources'][0]['data']['password'] | b64decode }}"
        awx_postgres_database: "{{ postgres_configuration['resources'][0]['data']['database'] | b64decode }}"
        awx_postgres_port: "{{ postgres_configuration['resources'][0]['data']['port'] | b64decode }}"
        awx_postgres_host: "{{ postgres_configuration['resources'][0]['data']['host'] | b64decode }}"

  when:
    - not external_database | bool
